// One-shot: download the latin woff2 subsets we use into public/fonts/ and emit
// src/ui/fonts.css with local @font-face rules. Run: node scripts/build-fonts.mjs
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = resolve(ROOT, 'public/fonts');
const OUT_CSS = resolve(ROOT, 'src/ui/fonts.css');
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FAMILIES = [
  'Fraunces:ital,wght@0,300;0,400;0,500;1,400;1,500',
  'Hanken+Grotesk:wght@400;500;600;700',
  'JetBrains+Mono:wght@400;500',
];

const slug = (fam, style, weight) =>
  `${fam.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${style}-${weight}`;

async function run() {
  await mkdir(FONT_DIR, { recursive: true });
  const faces = [];

  for (const q of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${q}&display=swap`;
    const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
    const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
    let m;
    while ((m = re.exec(css))) {
      const [, subset, body] = m;
      if (subset !== 'latin') continue;
      const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
      const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? 'normal';
      const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? '400';
      const src = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
      if (!family || !src) continue;

      const name = slug(family, style, weight) + '.woff2';
      const bytes = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(resolve(FONT_DIR, name), bytes);
      faces.push(
        `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${name}') format('woff2');\n}`,
      );
      console.log(`✔ ${name} (${(bytes.length / 1024).toFixed(0)} KB)`);
    }
  }

  await writeFile(
    OUT_CSS,
    `/* Generated by scripts/build-fonts.mjs — self-hosted latin subsets. */\n${faces.join('\n')}\n`,
  );
  console.log(`\nWrote ${faces.length} @font-face rules to src/ui/fonts.css`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
